config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :searches, only: [:index, :create] do
    collection do
      post :resolve_queries
      delete :delete_incomplete_queries
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "searches#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/search.rb
class Search < ApplicationRecord
  validates :user_ip_address, presence: true
  validates :query, presence: true

  # Method to retrieve incomplete searches based on a user's IP address
  def self.incomplete_search(ip_address)
    where(user_ip_address: ip_address, completed: false)
  end

  # Method to delete incomplete searches if a query isn't submitted
  def self.delete_incomplete_queries
    where(completed: false).delete_all
  end

  # Method to retrieve a user's ranked query history based on count and IP address
  def self.search_history(ip_address)
    where(user_ip_address: ip_address, completed: true).order('count DESC')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    user_ip_address = request.remote_ip
    @search_history = Search.search_history(user_ip_address)
  end

  def create
    user_ip_address = request.remote_ip
    query = params[:query].downcase
    Search.create(user_ip_address:, query:, completed: false)
    matching_searches = Search.where('query LIKE ?', "%#{query}%").where(completed: true).pluck(:query)
    render json: { status: '200', suggestions: matching_searches }
  end

  def resolve_queries
    user_ip_address = request.remote_ip
    final_query = params[:query].downcase
    @incomplete_searches = Search.incomplete_search(user_ip_address)
    saved_query = Search.find_by(query: final_query, user_ip_address:, completed: true)
    if saved_query
      saved_query.count += 1
      saved_query.save
      new_query = saved_query
    else
      new_query = Search.create(user_ip_address:, query: final_query, completed: true, count: 1)
    end
    @incomplete_searches.destroy_all
    render json: { status: '200', new_query: }
  end

  def delete_incomplete_queries
    Search.delete_incomplete_queries
    render json: { status: '200' }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="icon" href="<%= asset_url('LukApp_logo.png') %>" class="rounded-full" />
    <title>LukApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container w-full min-h-screen p-4 bg-sky-50">
      <%= yield %>
    </main>
  </body>
</html>

app/views/searches/index.html.erb
<div data-controller="search-logic" class="w-full">
    <%= image_tag "LukApp_logo.png", alt: "LukApp logo", width: 150, height: 150, class: "rounded-full mx-auto mt-6 border-4 border-gray-400" %>
    <div class="w-fit mx-auto mt-12">
        <%= form_with url: resolve_queries_searches_path, method: :post, data: { action: 'submit->search-logic#resolveSearches' } do |f| %>
            <%= f.text_field :query, placeholder: 'Look something up...', class: "w-80 border-2 border-gray-400 rounded-md", data: { search_logic_target: 'input' } %>
            <%= f.submit 'Search', data: { search_logic_target: 'submit_button'}, class: "bg-sky-600 font-semibold cursor-pointer p-2 rounded-md" %>
        <% end %>
        <ul data-search-logic-target="suggestions" class="mt-2">
        </ul>
    </div>
    <hr class="my-6 border-t-1 border-sky-400">
    <div>
        <h4 class="w-fit mx-auto font-semibold text-stone-700 text-lg mb-6">Your Top Searches:</h4>        
        <ul data-search-logic-target="history" class="w-1/2 mx-auto bg-white border border-gray-400 px-8 py-4 rounded-md">
            <% if @search_history %>
                <% @search_history.each do |search| %>
                    <li class="flex justify-between items-center w-full gap-14 text-stone-600">
                        <h5 class="text-lg"><%= search.query %></h5>
                        <p class="text-md">search count: <%= search.count %></p>
                    </li>
                <% end %>
            <% end %>
        </ul>
    </div>
</div>